# Generated by Django 4.2.5 on 2023-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='detail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
