# Generated by Django 4.2.5 on 2023-09-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Majors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('completed_total', models.IntegerField(default=0)),
                ('completed_common', models.IntegerField(default=0)),
                ('completed_major', models.IntegerField(default=0)),
                ('completed_submajor1', models.IntegerField(default=0, null=True)),
                ('completed_submajor2', models.IntegerField(default=0, null=True)),
                ('completed_english', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prime', models.BooleanField()),
                ('completed', models.IntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_submajor', to='Majors.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submajor', to='Users.user')),
            ],
        ),
    ]
