# Generated by Django 4.2.5 on 2023-09-14 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_number', models.IntegerField(unique=True)),
                ('student_year', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('completed_total', models.IntegerField(default=0)),
                ('completed_common', models.IntegerField(default=0)),
                ('completed_major', models.IntegerField(default=0)),
                ('completed_submajor', models.IntegerField(default=0)),
                ('completed_english', models.IntegerField(default=0)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_students', to='Lectures.major')),
                ('submajor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submajor_students', to='Lectures.major')),
            ],
        ),
    ]
