# Generated by Django 4.2.5 on 2023-09-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='submajor',
        ),
        migrations.CreateModel(
            name='Submajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submajor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_submajor', to='Lectures.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submajor', to='Users.user')),
            ],
        ),
    ]
