# Generated by Django 4.2.5 on 2023-09-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
