# Generated by Django 4.2.5 on 2023-09-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_primary_major_alter_user_secondary_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentnumber',
            name='number',
            field=models.IntegerField(),
        ),
    ]
