# Generated by Django 4.2.5 on 2023-09-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
