# Generated by Django 4.2.5 on 2023-09-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_studentnumber_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=25)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumbers'),
        ),
    ]
