# Generated by Django 4.2.5 on 2023-09-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0005_alter_category_student_numbers_and_more'),
        ('Users', '0004_studentnumbers_alter_user_student_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentNumber',
        ),
    ]
