# Generated by Django 4.2.5 on 2023-11-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGTclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='former',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
