# Generated by Django 4.2.5 on 2023-09-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0001_initial'),
        ('Users', '0004_alter_user_student_number'),
        ('CSEclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category19_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category20_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category21_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category22_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category23_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category24_CSE_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='former',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CSE_latter', to='CSEclasses.lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majortech_CSE_lecture', to='CSEclasses.majortech'),
        ),
        migrations.AlterField(
            model_name='majortech',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSE_tech', to='Majors.major'),
        ),
        migrations.AlterField(
            model_name='majortrack',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_CSEtrack', to='Majors.major'),
        ),
        migrations.AlterField(
            model_name='majortrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_CSEtrack', to='CSEclasses.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSE_track', to='Majors.major'),
        ),
        migrations.AlterField(
            model_name='track',
            name='student_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CSE_studentyear_track', to='Users.studentyear'),
        ),
    ]
