# Generated by Django 4.2.5 on 2023-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSEclasses', '0002_alter_lecture_category19_alter_lecture_category20_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='grade_recommend',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester_one',
            field=models.IntegerField(blank=True, choices=[(1, 'low'), (2, 'mid'), (3, 'high')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester_two',
            field=models.IntegerField(blank=True, choices=[(1, 'low'), (2, 'mid'), (3, 'high')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teamplay',
            field=models.IntegerField(blank=True, choices=[(1, 'none'), (2, 'little'), (3, 'average'), (4, 'much'), (5, 'full')]),
        ),
    ]
