# Generated by Django 4.2.5 on 2023-09-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmapdetail',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='roadmapdetaillecture',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='roadmapdetaillecture',
            name='roadmap_detail',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.DeleteModel(
            name='RoadmapDetail',
        ),
        migrations.DeleteModel(
            name='RoadmapDetailLecture',
        ),
    ]
