# Generated by Django 4.2.5 on 2023-10-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='track',
        ),
    ]
