# Generated by Django 4.2.5 on 2023-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roadmaps', '0002_remove_roadmap_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
