from django.core.management.base import BaseCommand
from MGTclasses.models import *
from Majors.models import *

class Command(BaseCommand):    
    Lecture = [
                {
                    'title': '경제학원론I',
                    'code':'ECO2001',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '경제학원론II',
                    'code':'ECO2002',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '경영통계학',
                    'code':'MGT2002',
                    'point': 3,
                    'semester_one': 12,
                    'semester_two': 13,
                    'teamplay': 2,
                    'grade_recommend': 1,
                    'season_open': 1,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': 'BA'
                },
                {
                    'title': '경제통계학',
                    'code':'ECO2004',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '통계학입문',
                    'code':'MAT3020',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '응용수학I',
                    'code':'MAT2410',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '대학수학',
                    'code': 'STS2004',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '미적분학I',
                    'code': 'STS2005',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '미적분학II',
                    'code': 'STS2006',
                    'point': 3,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공입문교과',
                    'category22': '전공입문교과',
                    'category21': '전공입문교과',
                    'category23_d': '선택',
                    'category22_d': '선택',
                    'category21_d': '선택',
                    'tech': None
                },
                {
                    'title': '회계학원론',
                    'code': 'MGT2003',
                    'point': 3,
                    'semester_one': 17,
                    'semester_two': 17,
                    'teamplay': 0,
                    'grade_recommend': 1~2,
                    'season_open': 1,
                    'category23': '전공필수교과',
                    'category22': '전공필수교과',
                    'category21': '전공필수교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '조직행동이론',
                    'code': 'MGT3001',
                    'point': 3,
                    'semester_one': 12,
                    'semester_two': 14,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공필수교과',
                    'category22': '전공필수교과',
                    'category21': '전공필수교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '인사조직'
                },
                {
                    'title': '생산관리론',
                    'code': 'MGT3003',
                    'point': 3,
                    'semester_one': 13,
                    'semester_two': 15,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공필수교과',
                    'category22': '전공필수교과',
                    'category21': '전공필수교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '재무관리',
                    'code': 'MGT3004',
                    'point': 3,
                    'semester_one': 11,
                    'semester_two': 15,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공필수교과',
                    'category22': '전공필수교과',
                    'category21': '전공필수교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '마케팅원론',
                    'code': 'MGT3006',
                    'point': 3,
                    'semester_one': 12,
                    'semester_two': 17,
                    'teamplay': 4,
                    'grade_recommend': 2~3,
                    'season_open': 0,
                    'category23': '전공필수교과',
                    'category22': '전공필수교과',
                    'category21': '전공필수교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '경영정보시스템',
                    'code': 'MGT3002',
                    'point': 3,
                    'semester_one': 9,
                    'semester_two': 11,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': '필수',
                    'category22_d': '필수',
                    'category21_d': '필수',
                    'tech': 'MIS'
                },
                {
                    'title': '관리회계',
                    'code': 'MGT3005',
                    'point': 3,
                    'former': '회계학원론',
                    'semester_one': 14,
                    'semester_two': 11,
                    'teamplay': 0,
                    'grade_recommend': 2~3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': '필수',
                    'category22_d': '필수',
                    'category21_d': '필수',
                    'tech': '회계'
                },
                {
                    'title': '국제경영론',
                    'code': 'MGT3007',
                    'point': 3,
                    'semester_one': 15,
                    'semester_two': 16,
                    'teamplay': 3,
                    'grade_recommend': 2~3,
                    'season_open': 1,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': '필수',
                    'category22_d': '필수',
                    'category21_d': '필수',
                    'tech': '국제경영'
                },
                {
                    'title': '경영전략',
                    'code': 'MGT4102',
                    'point': 3,
                    'semester_one': 12,
                    'semester_two': 8,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 1,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': '필수',
                    'category22_d': '필수',
                    'category21_d': '필수',
                    'tech': '전략'
                },
                {
                    'title': '기업윤리',
                    'code': 'MGT4105',
                    'point': 3,
                    'semester_one': 2,
                    'semester_two': 0,
                    'teamplay': 3,
                    'grade_recommend': 2,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': '필수',
                    'category22_d': '필수',
                    'category21_d': '필수',
                    'tech': '기타'
                },
############################ base ################################
                {
                    'title': '현대기업과기업윤리',
                    'code': 'MGT2001',
                    'point': 3,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '경영전략시뮬레이션',
                    'code': 'MGT4101',
                    'point': 3,
                    'former': '경영전략',
                    'semester_one': 2,
                    'semester_two': 0,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '전략'
                },
                {
                    'title': '조직구조와전략',
                    'code': 'MGT4103',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 3,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '인사조직'
                },
                {
                    'title': '리더쉽이론',
                    'code': 'MGT4104',
                    'point': 3,
                    'former': '조직행동이론',
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '인사조직'
                },
                {
                    'title': '인적자원관리',
                    'code': 'MGT4106',
                    'point': 3,
                    'former': None,
                    'semester_one': 5,
                    'semester_two': 5,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '인사조직'
                },
                {
                    'title': '노사관계론',
                    'code': 'MGT4107',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '인사조직'
                },
                {
                    'title': '기업지배구조와기업전략',
                    'code': 'MGTG109',
                    'point': 3,
                    'former': '경영전략',
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '전략'
                },
                {
                    'title': '기업윤리와실천적경영인재',
                    'code': 'MGT4110',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '의사결정론',
                    'code': 'MGT4201',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 4,
                    'semester_two': 6,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '통계자료분석',
                    'code': 'MGT4202',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 3,
                    'semester_two': 4,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '경영과학',
                    'code': 'MGT4203',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 6,
                    'semester_two': 6,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '시뮬레이션',
                    'code': 'MGT4204',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 2,
                    'semester_two': 0,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '계량경영분석모형최신주제및사례연구',
                    'code': 'MGT4205',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                   'grade_recommend': 1,
                  'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '경영환경에서의시계열자료분석과예측(캡스톤디자인)',
                    'code': 'MGT4206',
                    'point': 3,
                    'former': '경영통계학',
                    'semester_one': 0,
                    'semester_two': 4,
                    'teamplay': 4,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': 'BA인공지능',
                    'code': 'MGT4207',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 2,
                    'teamplay': 3,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'BA'
                },
                {
                    'title': '웹데이터수집과 텍스트분석(캡스톤디자인)',
                    'code': 'MGT4208',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 3,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '전자상거래개론',
                    'code': 'MGT4224',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 3,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '경영과정보기술',
                    'code': 'MGT4221',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 1,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'MIS'
                },
                {
                    'title': '모바일통신경영',
                    'code': 'MGT4222',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 1,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '글로벌혁신전략',
                    'code': 'MGT4616',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '정보기술과글로벌소셜비즈니스모델(캡스톤디자인)',
                    'code': 'MGT4223',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'MIS'
                },
                {
                    'title': '전사적자원관리소프트웨어활용',
                    'code': 'MGT4225',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '빅데이터와비즈니스모델',
                    'code': 'MGT4226',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '빅데이터와비즈니스인텔리젼스',
                    'code': 'MGT4226',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '디지털변혁과비즈니스모델혁신',
                    'code': 'MGT4227',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'MIS'
                },
                {
                    'title': '미래창업을위한창의성과창의경영',
                    'code': 'MGT4229',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '비즈니스앱개발',
                    'code': 'MGT4230',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '인공지능과경영모델',
                    'code': 'MGT4231',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '기술경영과기술사업화',
                    'code': 'MGT4241',
                    'point': 3,
                    'former': None,
                    'semester_one': 4,
                    'semester_two': 2,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '기술경영',
                    'code': 'MGT4241',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '생산계획및재고통제',
                    'code': 'MGT4242',
                    'point': 3,
                    'former': '생산관리론',
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '경영품질의이해',
                    'code': 'MGT4243',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 0,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '로지스틱스와생산전략',
                    'code': 'MGTG244',
                    'point': 3,
                    'former': '생산관리론',
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '정보화시대의기업경영과혁신',
                    'code': 'MGT4245',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '서비스기업운영관리론',
                    'code': 'MGT4246',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '공급체인관리와e-Business',
                    'code': 'MGT4247',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 2,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': 'LSOM'
                },
                {
                    'title': '비즈니스프로세스관리',
                    'code': 'MGT4248',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 1,
                    'teamplay': 1,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '종합물류론',
                    'code': 'MGT4249',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '해상운송론',
                    'code': 'MGT4250',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '투자론',
                    'code': 'MGT4301',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 5,
                    'semester_two': 3,
                    'teamplay': 0,
                    'grade_recommend': 2~3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '기업재무론',
                    'code': 'MGT4302',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '파생상품론',
                    'code': 'MGT4303',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 5,
                    'semester_two': 4,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '포트폴리오관리',
                    'code': 'MGT4304',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 2,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '금융리스크관리',
                    'code': 'MGT4231',
                    'point': 3,
                    'former': '재무관리, 경영통계학',
                    'semester_one': 1,
                    'semester_two': 2,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '금융기관론',
                    'code': 'MGT4307',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 2,
                    'semester_two': 2,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '벤처캐피탈과투자분석(캡스톤디자인)',
                    'code': 'MGT4308',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 3,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '고급재무이론',
                    'code': 'MGT4309',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '가치평가이론과실무',
                    'code': 'MGTG310',
                    'point': 3,
                    'former': '재무관리',
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '재무'
                },
                {
                    'title': '금융위기와 금융산업 혁신',
                    'code': 'MGT4316',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '금융투자산업의이해(캡스톤디자인)',
                    'code': 'MGT4312',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '벤처와금융시장(캡스톤디자인)',
                    'code': 'MGT4313',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
               
                {
                    'title': '보험학원론',
                    'code': 'MGT4331',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '보험'
                },
                
                {
                    'title': '중급회계I',
                    'code': 'MGT4401',
                    'point': 3,
                    'former': '회계학원론',
                    'semester_one': 6,
                    'semester_two': 5,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '중급회계II',
                    'code': 'MGT4402',
                    'point': 3,
                    'former': '중급회계1',
                    'semester_one': 3,
                    'semester_two': 5,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '고급회계',
                    'code': 'MGT4403',
                    'point': 3,
                    'former': '중급회계II',
                    'semester_one': 2,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '원가회계',
                    'code': 'MGT4404',
                    'point': 3,
                    'former': '관리회계',
                    'semester_one': 3,
                    'semester_two': 2,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '세무회계',
                    'code': 'MGT4406',
                    'point': 3,
                    'former': '중급회계2',
                    'semester_one': 0,
                    'semester_two': 3,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '회계감사',
                    'code': 'MGT4407',
                    'point': 3,
                     'former': '중급회계2, 원가회계',
                    'semester_one': 3,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '회계'
                },
                {
                    'title': '메타버스가상시장과마케팅사이언스',
                    'code': 'MGT4517',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 1,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '창업의이해(캡스톤디자인)',
                    'code': 'MGT4615',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                
                {
                    'title': '이해관계자자본주의와ESG',
                    'code': 'MGT4718',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 0,
                    'teamplay': 2,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '프로세스 수익경영',
                    'code': 'MGT4251',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 1,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
             
                {
                    'title': '시계열자료분석과예측',
                    'code': 'MGTG705',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 4,
                    'grade_recommend': 4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '회계/재무정보분석의이해와응용',
                    'code': 'MGTG706',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '응용경영통계',
                    'code': 'MGT4207',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
               
                {
                    'title': '마케팅전략',
                    'code': 'MGT4501',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '소비자행동론',
                    'code': 'MGT4502',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 2,
                    'semester_two': 3,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '시장조사론',
                    'code': 'MGT4503',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 2,
                    'semester_two': 2,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '제품정책론',
                    'code': 'MGT4504',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '브랜드전략론',
                    'code': 'MGTG505',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '촉진전략론',
                    'code': 'MGT4506',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '유통전략론',
                    'code': 'MGT4507',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 2,
                    'semester_two': 3,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '서비스마케팅',
                    'code': 'MGT4508',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 2,
                    'semester_two': 2,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '국제마케팅론',
                    'code': 'MGT4510',
                    'point': 3,
                    'former': '마케팅원론',
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '마케팅관리',
                    'code': 'MGT4511',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                     'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                 'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '마케팅최신주제및사례연구',
                    'code': 'MGT4513',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 3,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '빅데이터기반마케팅과스타트업',
                    'code': 'MGT4515',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '빅데이터마케팅',
                    'code': 'MGT4515',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '인공지능과마케팅',
                    'code': 'MGT4516',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 3,
                    'teamplay': 3,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '마케팅'
                },
                {
                    'title': '기업과국제환경',
                    'code': 'MGT4601',
                    'point': 3,
                    'former': None,
                    'semester_one': 4,
                    'semester_two': 3,
                    'teamplay': 2,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '다국적기업론',
                    'code': 'MGT4602',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 1,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '국제재무관리',
                    'code': 'MGT4603',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '국제경영전략',
                    'code': 'MGT4604',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 1,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '무역경영관리',
                    'code': 'MGT4605',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 3,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '국제금융시장론',
                    'code': 'MGT4607',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '외환론',
                    'code': 'MGT4609',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '중국시장및경영환경의이해',
                    'code': 'MGT4613',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 2,
                    'teamplay': 0,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '글로벌 혁신 전략',
                    'code': 'MGT4616',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 2,
                    'grade_recommend': 3,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '국제경영'
                },
                {
                    'title': '글로벌통합모듈',
                    'code': 'MGT4614',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '경영영어라이팅',
                    'code': 'MGT4701',
                    'point': 3,
                    'former': None,
                    'semester_one': 2,
                    'semester_two': 3,
                    'teamplay': 0,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '기업법',
                    'code': 'MGT4702',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': 'CEO경영특강',
                    'code': 'MGT4704',
                    'point': 2,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 1,
                    'teamplay': 1,
                    'grade_recommend': 2,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '기타'
                },
                {
                    'title': '경영인턴십',
                    'code': 'MGT4705',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '경영현장실습',
                    'code': 'MGT4706',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 0,
                    'grade_recommend': 4,
                    'season_open': 1,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': '기타'
                },
                {
                    'title': '글로벌인턴십(현장실습중심)',
                    'code': 'MGT4707',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '사회적기업인턴십',
                    'code': 'MGT4708',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '글로벌리더십실습',
                    'code': 'MGT4710',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '산업분석연구',
                    'code': 'MGT4711',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '지식,인성그리고경영',
                    'code': 'MGT4712',
                    'point': 3,
                    'former': None,
                    'semester_one': 3,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '지식경영과서비스혁신',
                    'code': 'MGT4227',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 2~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '사회적가치창출프랙티컴',
                    'code': 'MGT4713',
                    'point': 3,
                    'former': None,
                    'semester_one': 1,
                    'semester_two': 1,
                    'teamplay': 2,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '사회적기업창업과운영',
                    'code': 'MGT4714',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '금융비즈니스인턴십',
                    'code': 'MGT4715',
                    'point': 6,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '글로벌인턴십(프로젝트중심)',
                    'code': 'MGT4716',
                    'point': 3,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 0,
                    'teamplay': 4,
                    'grade_recommend': 1,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                },
                {
                    'title': '지식,인성그리고경영(심화)',
                    'code': 'MGT4717',
                    'point': 1,
                    'former': None,
                    'semester_one': 0,
                    'semester_two': 3,
                    'teamplay': 4,
                    'grade_recommend': 3~4,
                    'season_open': 0,
                    'category23': '전공선택교과',
                    'category22': '전공선택교과',
                    'category21': '전공선택교과',
                    'category23_d': None,
                    'category22_d': None,
                    'category21_d': None,
                    'tech': None
                }

                # {
                #     'title': '관리회계',
                #     'code':'ECO2001',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 1,
                #     'season_open': 0,
                #     'category23': '전공선택교과',
                #     'category22': '전공선택교과',
                #     'category21': '전공선택교과',
                #     'category23_d': '필수',
                #     'category22_d': '필수',
                #     'category21_d': '필수',
                #     'tech': '회계'
                # },
                # {
                #     'title': '마케팅원론',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공필수교과',
                #     'category22': '전공필수교과',
                #     'category21': '전공필수교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '마케팅'
                # }, 
                # {
                #     'title': '조직행동이론',
                #     'code':'ECO2001',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 1,
                #     'season_open': 0,
                #     'category23': '전공필수교과',
                #     'category22': '전공필수교과',
                #     'category21': '전공필수교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '인사조직'
                # },
                # {
                #     'title': '재무관리',
                #     'code':'EC2O2001',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 1,
                #     'season_open': 0,
                #     'category23': '전공필수교과',
                #     'category22': '전공필수교과',
                #     'category21': '전공필수교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '재무보험'
                # },
                # {
                #     'title': '생산관리론',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공필수교과',
                #     'category22': '전공필수교과',
                #     'category21': '전공필수교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '국제경영'
                # }, 
                # {
                #     'title': '회계학원론',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 4,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공필수교과',
                #     'category22': '전공필수교과',
                #     'category21': '전공필수교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '회계'
                # }, 
                # {
                #     'title': '경영정보시스템',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 2,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공선택교과',
                #     'category22': '전공선택교과',
                #     'category21': '전공선택교과',
                #     'category23_d': '필수',
                #     'category22_d': '필수',
                #     'category21_d': '필수',
                #     'tech': 'BA/LSOM/MIS'
                # },
                # {
                #     'title': '인적자원관리',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 2,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공선택교과',
                #     'category22': '전공선택교과',
                #     'category21': '전공선택교과',
                #     'category23_d': '필수',
                #     'category22_d': '필수',
                #     'category21_d': '필수',
                #     'tech': '인사조직',
                #     'former' : '조직행동이론',
                # }, 
                # {
                #     'title': 'CEO 경영특강',
                #     'code':'MGT3009',
                #     'point': 3,
                #     'semester_one': 3,
                #     'semester_two': 3,
                #     'teamplay': 2,
                #     'grade_recommend': 2,
                #     'season_open': 0,
                #     'category23': '전공선택교과',
                #     'category22': '전공선택교과',
                #     'category21': '전공선택교과',
                #     'category23_d': None,
                #     'category22_d': None,
                #     'category21_d': None,
                #     'tech': '기타'
                # } 
    ]
            
    
    
    for data in Lecture:
         if 'label' not in data:
            data['label'] = data['title']
    def handle(self, *args, **options):
            i=0
            for lecture in self.Lecture:
                lec = Lecture(
                title = lecture['title'], 
                code = lecture['code'], 
                point = lecture['point'], 
                semester_one = lecture['semester_one'], 
                semester_two = lecture['semester_two'], 
                teamplay = lecture['teamplay'], 
                season_open = lecture['season_open'], 
                grade_recommend = lecture['grade_recommend'],
                category23 = Category.objects.get( title = lecture['category23'], detail = lecture['category23_d']),
                category22 = Category.objects.get( title = lecture['category22'], detail = lecture['category22_d']),            
                category21 = Category.objects.get( title = lecture['category21'], detail = lecture['category21_d']),
                teach = 0,
                advance = 0
                )
                if (lecture['tech']) is not None:
                    lec.tech = MajorTech.objects.get( title = lecture['tech'])
                former_code = lecture.get('former')
                if former_code:
                    try:
                        lec.former = Lecture.objects.get(code=former_code)
                    except Lecture.DoesNotExist:
                        pass
                lec.save()
                
            self.stdout.write(self.style.SUCCESS('MGT Lectures initialized'))
            return 0