# Generated by Django 4.2.5 on 2023-11-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Majors', '0001_initial'),
        ('Commonclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommonlecture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commonlecture_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category21_common_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category22_common_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category23_common_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category24_common_lecture', to='Majors.category'),
        ),
    ]
