# Generated by Django 4.2.5 on 2023-09-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0001_initial'),
        ('Commonclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category19_common_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category20_common_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category21_common_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category23_common_lecture', to='Majors.category'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='category24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category24_common_lecture', to='Majors.category'),
        ),
    ]
