from django.core.management.base import BaseCommand
from Majors.models import *
from CSEclasses.models import *

class Command(BaseCommand):
    Lectures = [
        {   'title': '미적분학I',
            'code':'STS2005',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '미적분학II',
            'code':'STS2006',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '일반물리실험I',
            'code':'PHY1101',
            'point': 1,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '일반물리I',
            'code':'PHY1001',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '응용수학I',
            'code':'MAT2410',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '응용수학II',
            'code':'MAT2420',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {
            'title': '집합론',
            'code':'MAT2010',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '선형대수학',
            'code':'MAT2110',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '정수론',
            'code':'MAT2120',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '고급응용C프로그래밍',
            'code':'STS2008',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '기초C언어',
            'code':'CSW2010',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '일반물리II',
            'code':'PHY1002',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {
            'title': '컴퓨터프로그래밍I (구: 기초공학설계)',
            'code':'CSE2003',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터프로그래밍II (구: C프로그래밍)',
            'code':'CSE2035',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '이산구조',
            'code':'CSE3006',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터공학설계및실험I',
            'code':'CSE3013',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '디지털회로개론',
            'code':'CSE3015',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        # {
        #     'title': '디지털회로설계',
        #     'code':'EEE2135',
        #     'point': 3,
        #     'semester_one': 3,
        #     'semester_two': 3,
        #     'teamplay': 1,
        #     'former': None,
        #     'grade_recommend': 1,
        #     'season_open': 1,
        #     'category23': '전공필수교과',
        #     'category22': '전공필수교과',
        #     'category21': '전공필수교과',
        #     'category23_d': None,
        #     'category22_d': None,
        #     'category21_d': None,
        #     'tech' : None
        # },
        {
            'title': '컴퓨터공학실험II',
            'code':'CSE3016',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '자료구조',
            'code':'CSE3080',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '운영체제',
            'code':'CSE4070',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '멀티코어 프로그래밍',
            'code':'CSE4100',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '고급소프트웨어실습I',
            'code':'CSE4152',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '캡스톤디자인II',
            'code':'CSE4187',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '캡스톤디자인I',
            'code':'CSE4186',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '인턴쉽I',
            'code':'CSE4190',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '알고리즘설계와분석',
            'code':'CSE3081',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터교과교육론',
            'code':'CSEQ981',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터학교과교재연구및지도법',
            'code':'CSEQ982',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터학교과논리및논술',
            'code':'CSEQ983',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        # {
        #     'title': '컴퓨터아키텍쳐',
        #     'code':'CSE4010',
        #     'point': 3,
        #     'semester_one': 3,
        #     'semester_two': 3,
        #     'teamplay': 1,
        #     'former': None,
        #     'grade_recommend': 1,
        #     'season_open': 1,
        #     'category23': '전공선택교과',
        #     'category22': '전공선택교과',
        #     'category21': '전공선택교과',
        #     'category23_d': None,
        #     'category22_d': None,
        #     'category21_d': None,
        #     'tech' : None
        # },
        {
            'title': '컴퓨터아키텍쳐',
            'code':'EEE3178',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '프로그래밍언어',
            'code':'CSE4050',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '데이터베이스시스템',
            'code':'CSE4110',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '소프트웨어공학',
            'code':'CSE4115',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터네트워크',
            'code':'CSE4175',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초인공지능',
            'code':'CSE4185',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초머신러닝',
            'code':'CSE4130',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초컴퓨터그래픽스',
            'code':'CSE4170',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '암호학기초',
            'code':'CSE4188',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },

    ]
    def handle(self, *args, **options):
        for lecture in self.Lectures:
            lec = Lecture(
            title = lecture['title'], 
            code = lecture['code'], 
            point = lecture['point'], 
            semester_one = lecture['semester_one'], 
            semester_two = lecture['semester_two'], 
            teamplay = lecture['teamplay'], 
            season_open = lecture['season_open'], 
            grade_recommend = lecture['grade_recommend'], 
            category23 = Category.objects.get( title = lecture['category23'], detail = lecture['category23_d']),
            category22 = Category.objects.get( title = lecture['category22'], detail = lecture['category22_d']),            
            category21 = Category.objects.get( title = lecture['category21'], detail = lecture['category21_d']),
            teach = 0,
            advance = 0
            )
            if (lecture['tech']) is not None:
                lec.tech = MajorTech.objects.get( title = lecture['tech'])
            former_title = lecture.get('former')

            if former_title:
                    try:
                        lec.former = Lecture.objects.get(title=former_title)
                    except Lecture.DoesNotExist:
                        pass
            lec.save()
        self.stdout.write(self.style.SUCCESS('Lectures initialized'))
        return 0