from django.core.management.base import BaseCommand
from Majors.models import *
from CSEclasses.models import *

class Command(BaseCommand):
    Lectures = [
        {   'title': '미적분학I',
            'code':'STS2005',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '미적분학II',
            'code':'STS2006',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '일반물리실험I',
            'code':'PHY1101',
            'point': 1,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '일반물리I',
            'code':'PHY1001',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '응용수학I',
            'code':'MAT2410',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {   'title': '응용수학II',
            'code':'MAT2420',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {
            'title': '집합론',
            'code':'MAT2010',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '선형대수학',
            'code':'MAT2110',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '정수론',
            'code':'MAT2120',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '고급응용C프로그래밍',
            'code':'STS2008',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '기초C언어',
            'code':'CSW2010',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '선택',
            'category22_d': '선택',
            'category21_d': '선택',
            'tech' : None
        },
        {
            'title': '일반물리II',
            'code':'PHY1002',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공입문교과',
            'category22': '전공입문교과',
            'category21': '전공입문교과',
            'category23_d': '필수',
            'category22_d': '필수',
            'category21_d': '필수',
            'tech' : None
        },
        {
            'title': '컴퓨터프로그래밍I(구 기초공학설계)',
            'code':'CSE2003',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터프로그래밍II(구 C프로그래밍)',
            'code':'CSE2035',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE2003',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '이산구조',
            'code':'CSE3006',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터공학설계및실험I',
            'code':'CSE3013',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE2035',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '디지털회로개론',
            'code':'CSE3015',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        # {
        #     'title': '디지털회로설계',
        #     'code':'EEE2135',
        #     'point': 3,
        #     'semester_one': 3,
        #     'semester_two': 3,
        #     'teamplay': 1,
        #     'former': None,
        #     'grade_recommend': 1,
        #     'season_open': 1,
        #     'category23': '전공필수교과',
        #     'category22': '전공필수교과',
        #     'category21': '전공필수교과',
        #     'category23_d': None,
        #     'category22_d': None,
        #     'category21_d': None,
        #     'tech' : None
        # },
        {
            'title': '컴퓨터공학실험II',
            'code':'CSE3016',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '자료구조',
            'code':'CSE3080',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE2035',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '운영체제',
            'code':'CSE4070',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '멀티코어프로그래밍',
            'code':'CSE4100',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '고급소프트웨어실습I',
            'code':'CSE4152',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '캡스톤디자인II',
            'code':'CSE4187',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '캡스톤디자인I',
            'code':'CSE4186',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '인턴쉽I',
            'code':'CSE4190',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '알고리즘설계와분석',
            'code':'CSE3081',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터교과교육론',
            'code':'CSEQ981',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터학교과교재연구및지도법',
            'code':'CSEQ982',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터학교과논리및논술',
            'code':'CSEQ983',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공필수교과',
            'category22': '전공필수교과',
            'category21': '전공필수교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        # {
        #     'title': '컴퓨터아키텍쳐',
        #     'code':'CSE4010',
        #     'point': 3,
        #     'semester_one': 3,
        #     'semester_two': 3,
        #     'teamplay': 1,
        #     'former': None,
        #     'grade_recommend': 1,
        #     'season_open': 1,
        #     'category23': '전공선택교과',
        #     'category22': '전공선택교과',
        #     'category21': '전공선택교과',
        #     'category23_d': None,
        #     'category22_d': None,
        #     'category21_d': None,
        #     'tech' : None
        # },
        {
            'title': '컴퓨터아키텍쳐',
            'code':'EEE3178',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '프로그래밍언어',
            'code':'CSE4050',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '데이터베이스시스템',
            'code':'CSE4110',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '소프트웨어공학',
            'code':'CSE4115',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터네트워크',
            'code':'CSE4175',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초인공지능',
            'code':'CSE4185',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초머신러닝',
            'code':'CSE4130',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초컴퓨터그래픽스',
            'code':'CSE4170',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'STS2005',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '암호학기초',
            'code':'CSE4188',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
######################## base #################################
        {
            'title': '기초통계학',
            'code':'CSE1031',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'STS2006',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '고급 이산수학',
            'code':'CSE1032',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE1031',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '공학설계입문',
            'code':'CSE2004',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초 콤비네토릭스',
            'code':'CSE2007',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터공학 및 정보통신개론',
            'code':'CSE2009',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터시스템개론',
            'code':'CSE3030',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': 'JAVA언어',
            'code':'CSE3040',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터공학세미나I',
            'code':'CSE3050',
            'point': 1,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '연구프로젝트I',
            'code':'CSE3301',
            'point': 0,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '연구프로젝트II',
            'code':'CSE3302',
            'point': 0,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '연구프로젝트III',
            'code':'CSE3303',
            'point': 0,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '연구프로젝트IV',
            'code':'CSE3304',
            'point': 0,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터아키텍쳐',
            'code':'CSE4010',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3015',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '임베디드컴퓨터구조',
            'code':'CSE4011',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3015',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '지능형통신시스템',
            'code':'CSE4060',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터공학실험III',
            'code':'CSE4061',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '자동장치이론',
            'code':'CSE4085',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '파일처리',
            'code':'CSE4095',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3080',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '소프트웨어설계',
            'code':'CSE4105',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '데이터베이스프로그래밍',
            'code':'CSE4112',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '임베디드시스템소프트웨어',
            'code':'CSE4116',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초컴파일러구성',
            'code':'CSE4120',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '수치컴퓨팅및응용',
            'code':'CSE4140',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'STS2006',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '임베디드시스템개론',
            'code':'CSE4150',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '디지털시스템',
            'code':'CSE4155',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '그래프이론및알고리즘',
            'code':'CSE4158',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '유닉스프로그래밍',
            'code':'CSE4176',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '인터넷프로그래밍및응용',
            'code':'CSE4177',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초SoC설계',
            'code':'CSE4178',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': 'CSE3015',
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': 'SW경제성분석및창업',
            'code':'CSE4181',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '설계패턴',
            'code':'CSE4182',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': 'SW명세화기법',
            'code':'CSE4183',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '인터넷프로그래밍및응용',
            'code':'CSE4177',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '졸업프로젝트',
            'code':'CSE4199',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '대화형사용자인터페이스개론',
            'code':'CSEG311',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '데이터마이닝',
            'code':'CSEG312',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '인간언어기술개론',
            'code':'CSEG321',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '병렬분산컴퓨팅',
            'code':'CSEG414',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '패턴인식',
            'code':'CSEG416',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '컴퓨터비전',
            'code':'CSEG418',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '수치컴퓨팅및GPU프로그래밍',
            'code':'CSEG437',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '확장현실시스템',
            'code':'CSEG450',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '기초딥러닝',
            'code':'CSEG463',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': 'GPGPU컴퓨팅',
            'code':'CSEG483',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '계산적지능최적화',
            'code':'CSEG494',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '멀티미디어콘텐츠표현및처리',
            'code':'CSEG501',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '강화학습개론',
            'code':'CSEG516',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
        {
            'title': '공간데이터베이스시스템',
            'code':'CSEG601',
            'point': 3,
            'semester_one': 3,
            'semester_two': 3,
            'teamplay': 1,
            'former': None,
            'grade_recommend': 1,
            'season_open': 1,
            'category23': '전공선택교과',
            'category22': '전공선택교과',
            'category21': '전공선택교과',
            'category23_d': None,
            'category22_d': None,
            'category21_d': None,
            'tech' : None
        },
    ]
    def handle(self, *args, **options):
        for lecture in self.Lectures:
            lec = Lecture(
            title = lecture['title'], 
            code = lecture['code'], 
            point = lecture['point'], 
            semester_one = lecture['semester_one'], 
            semester_two = lecture['semester_two'], 
            teamplay = lecture['teamplay'], 
            season_open = lecture['season_open'], 
            grade_recommend = lecture['grade_recommend'], 
            category23 = Category.objects.get( title = lecture['category23'], detail = lecture['category23_d']),
            category22 = Category.objects.get( title = lecture['category22'], detail = lecture['category22_d']),            
            category21 = Category.objects.get( title = lecture['category21'], detail = lecture['category21_d']),
            teach = 0,
            advance = 0
            )
            if (lecture['tech']) is not None:
                lec.tech = MajorTech.objects.get( title = lecture['tech'])
            former_code = lecture.get('former')

            if former_code:
                    try:
                        lec.former = Lecture.objects.get(code=former_code)
                    except Lecture.DoesNotExist:
                        pass
            lec.save()
        self.stdout.write(self.style.SUCCESS('Lectures initialized'))
        return 0