# Generated by Django 4.2.5 on 2023-11-04 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Majors', '0001_initial'),
        ('Users', '0001_initial'),
        ('ECOclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userecolecture',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecolecture_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ECO_track', to='Majors.major'),
        ),
        migrations.AddField(
            model_name='track',
            name='student_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ECO_studentyear_track', to='Users.studentyear'),
        ),
        migrations.AddField(
            model_name='majortrack',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_ECOtrack', to='Majors.major'),
        ),
        migrations.AddField(
            model_name='majortrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_ECOtrack', to='ECOclasses.track'),
        ),
        migrations.AddField(
            model_name='majortech',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ECO_tech', to='Majors.major'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category21',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category21_ECO_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category22_ECO_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category23',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category23_ECO_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='category24',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category24_ECO_lecture', to='Majors.category'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='majortech_ECO_lecture', to='ECOclasses.majortech'),
        ),
    ]
