# Generated by Django 4.2.5 on 2023-09-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.category')),
                ('for_student_number', models.ManyToManyField(to='Users.studentnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_major', to='Users.major')),
                ('dual_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_major', to='Users.major')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.major')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=10)),
                ('credits', models.IntegerField()),
                ('eta_url', models.URLField()),
                ('semester_1', models.BooleanField()),
                ('semester_2', models.BooleanField()),
                ('team_project', models.BooleanField()),
                ('recommended_grade', models.CharField(max_length=10)),
                ('is_summer_offered', models.BooleanField()),
                ('is_education', models.BooleanField()),
                ('is_advanced', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.categorydetail')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.major')),
                ('prerequisite', models.ManyToManyField(blank=True, to='Lectures.subject')),
                ('tech', models.ManyToManyField(blank=True, to='Lectures.tech')),
            ],
        ),
    ]
