# Generated by Django 4.2.5 on 2023-09-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_advanced',
            field=models.BooleanField(null=True),
        ),
    ]
