# Generated by Django 4.2.5 on 2023-09-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_studentnumber_number'),
        ('Lectures', '0002_track_is_advanced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.major')),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumber')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.route')),
            ],
        ),
        migrations.CreateModel(
            name='TechInSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumber')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorydetail',
            name='for_student_number',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_summer_offered',
        ),
        migrations.AddField(
            model_name='category',
            name='student_numbers',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='category_detail',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Lectures.categorydetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorydetail',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Lectures.category'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='techinsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.subject'),
        ),
        migrations.AddField(
            model_name='techinsubject',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.tech'),
        ),
        migrations.AddField(
            model_name='subjectinroute',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.subject'),
        ),
        migrations.AddField(
            model_name='route',
            name='subjects',
            field=models.ManyToManyField(through='Lectures.SubjectInRoute', to='Lectures.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tech',
            field=models.ManyToManyField(blank=True, through='Lectures.TechInSubject', to='Lectures.tech'),
        ),
    ]
