# Generated by Django 4.2.5 on 2023-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0003_route_subjectinroute_techinsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='categorydetail',
            name='category',
        ),
    ]
