# Generated by Django 4.2.5 on 2023-09-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0004_categorydetails_remove_categorydetail_category'),
        ('Users', '0004_studentnumbers_alter_user_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='student_numbers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumbers'),
        ),
        migrations.AlterField(
            model_name='route',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumbers'),
        ),
        migrations.AlterField(
            model_name='techinsubject',
            name='student_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.studentnumbers'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.category'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.categorydetails'),
        ),
        migrations.DeleteModel(
            name='CategoryDetail',
        ),
    ]
